package net.edu.resprouted.datagen;

import net.edu.resprouted.block.ModBlocks;
import net.edu.resprouted.util.ModTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.block.Blocks;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }
    @Override
    protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                //SLATE
                .add(ModBlocks.SLATE)
                .add(ModBlocks.COBBLED_SLATE)
                .add(ModBlocks.COBBLED_SLATE_SLAB)
                .add(ModBlocks.COBBLED_SLATE_STAIRS)
                .add(ModBlocks.COBBLED_SLATE_WALL)
                .add(ModBlocks.POLISHED_SLATE)
                .add(ModBlocks.POLISHED_SLATE_SLAB)
                .add(ModBlocks.POLISHED_SLATE_STAIRS)
                .add(ModBlocks.POLISHED_SLATE_WALL)
                .add(ModBlocks.CHISELED_SLATE)
                .add(ModBlocks.SLATE_BRICKS)
                .add(ModBlocks.SLATE_BRICK_SLAB)
                .add(ModBlocks.SLATE_BRICK_STAIRS)
                .add(ModBlocks.SLATE_BRICK_WALL)
                .add(ModBlocks.SLATE_ROOFS)
                .add(ModBlocks.SLATE_ROOF_SLAB)
                .add(ModBlocks.SLATE_ROOF_STAIRS)
                .add(ModBlocks.SLATE_PILLAR)

                //ANDESITE
                .add(ModBlocks.ANDESITE_BRICKS)
                .add(ModBlocks.ANDESITE_BRICK_STAIRS)
                .add(ModBlocks.ANDESITE_BRICK_WALL)
                .add(ModBlocks.ANDESITE_BRICK_SLAB)
                .add(ModBlocks.CRACKED_ANDESITE_BRICKS)
                .add(ModBlocks.CHISELED_ANDESITE)
                .add(ModBlocks.ANDESITE_PILLAR)

                //DIORITE
                .add(ModBlocks.DIORITE_BRICKS)
                .add(ModBlocks.DIORITE_BRICK_STAIRS)
                .add(ModBlocks.DIORITE_BRICK_WALL)
                .add(ModBlocks.DIORITE_BRICK_SLAB)
                .add(ModBlocks.CRACKED_DIORITE_BRICKS)
                .add(ModBlocks.CHISELED_DIORITE)
                .add(ModBlocks.DIORITE_PILLAR)

                //GRANITE
                .add(ModBlocks.GRANITE_BRICKS)
                .add(ModBlocks.GRANITE_BRICK_STAIRS)
                .add(ModBlocks.GRANITE_BRICK_WALL)
                .add(ModBlocks.GRANITE_BRICK_SLAB)
                .add(ModBlocks.CRACKED_GRANITE_BRICKS)
                .add(ModBlocks.CHISELED_GRANITE)
                .add(ModBlocks.GRANITE_PILLAR)

                //STONE
                .add(ModBlocks.POLISHED_STONE)
                .add(ModBlocks.POLISHED_STONE_STAIRS)
                .add(ModBlocks.POLISHED_STONE_WALL)
                .add(ModBlocks.POLISHED_STONE_SLAB)
                .add(ModBlocks.STONE_PILLAR)
                .add(ModBlocks.GARGOYLE)

                //SANDSTONE
                .add(ModBlocks.SANDSTONE_BRICKS)
                .add(ModBlocks.SANDSTONE_BRICK_STAIRS)
                .add(ModBlocks.SANDSTONE_BRICK_WALL)
                .add(ModBlocks.SANDSTONE_BRICK_SLAB)
                .add(ModBlocks.SANDSTONE_PILLAR)

                //RED SANDSTONE
                .add(ModBlocks.RED_SANDSTONE_BRICKS)
                .add(ModBlocks.RED_SANDSTONE_BRICK_STAIRS)
                .add(ModBlocks.RED_SANDSTONE_BRICK_WALL)
                .add(ModBlocks.RED_SANDSTONE_BRICK_SLAB)
                .add(ModBlocks.RED_SANDSTONE_PILLAR)

                //WROUGHT IRON
                .add(ModBlocks.WROUGHT_IRON_BLOCK)
                .add(ModBlocks.CUT_WROUGHT_IRON_BLOCK)
                .add(ModBlocks.CUT_WROUGHT_IRON_STAIRS)
                .add(ModBlocks.CUT_WROUGHT_IRON_SLAB)
                .add(ModBlocks.WROUGHT_IRON_BULB)
                .add(ModBlocks.WROUGHT_IRON_BARS)

                //CHAINS
                .add(ModBlocks.GOLDEN_CHAIN)
                .add(ModBlocks.COPPER_CHAIN)
                .add(ModBlocks.EXPOSED_COPPER_CHAIN)
                .add(ModBlocks.WEATHERED_COPPER_CHAIN)
                .add(ModBlocks.OXIDIZED_COPPER_CHAIN)
                .add(ModBlocks.WAXED_COPPER_CHAIN)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_CHAIN)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_CHAIN)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_CHAIN)

                //CHANDELIER
                .add(ModBlocks.CHANDELIER)
                .add(ModBlocks.GOLDEN_CHANDELIER)
                .add(ModBlocks.COPPER_CHANDELIER)
                .add(ModBlocks.EXPOSED_COPPER_CHANDELIER)
                .add(ModBlocks.WEATHERED_COPPER_CHANDELIER)
                .add(ModBlocks.OXIDIZED_COPPER_CHANDELIER)
                .add(ModBlocks.WAXED_COPPER_CHANDELIER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_CHANDELIER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_CHANDELIER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_CHANDELIER)

                //LANTERNS
                .add(ModBlocks.GOLDEN_LANTERN)
                .add(ModBlocks.GOLDEN_SOUL_LANTERN)
                .add(ModBlocks.COPPER_LANTERN)
                .add(ModBlocks.EXPOSED_COPPER_LANTERN)
                .add(ModBlocks.WEATHERED_COPPER_LANTERN)
                .add(ModBlocks.OXIDIZED_COPPER_LANTERN)
                .add(ModBlocks.WAXED_COPPER_LANTERN)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_LANTERN)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_LANTERN)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_LANTERN)

                .add(ModBlocks.COPPER_SOUL_LANTERN)
                .add(ModBlocks.EXPOSED_COPPER_SOUL_LANTERN)
                .add(ModBlocks.WEATHERED_COPPER_SOUL_LANTERN)
                .add(ModBlocks.OXIDIZED_COPPER_SOUL_LANTERN)
                .add(ModBlocks.WAXED_COPPER_SOUL_LANTERN)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_SOUL_LANTERN)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_SOUL_LANTERN)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_SOUL_LANTERN)

                .add(ModBlocks.EVAPORATING_BASIN)

                //ALCHEMY
                .add(ModBlocks.CONDENSER)
                .add(ModBlocks.ADVANCED_CONDENSER)
                .add(ModBlocks.RETORT)
                .add(ModBlocks.ADVANCED_RETORT)

                //IRON CANDLE HOLDER
                .add(ModBlocks.IRON_CANDLE_HOLDER)
                .add(ModBlocks.WHITE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_GRAY_IRON_CANDLE_HOLDER)
                .add(ModBlocks.GRAY_IRON_CANDLE_HOLDER)
                .add(ModBlocks.BLACK_IRON_CANDLE_HOLDER)
                .add(ModBlocks.BROWN_IRON_CANDLE_HOLDER)
                .add(ModBlocks.RED_IRON_CANDLE_HOLDER)
                .add(ModBlocks.ORANGE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.YELLOW_IRON_CANDLE_HOLDER)
                .add(ModBlocks.LIME_IRON_CANDLE_HOLDER)
                .add(ModBlocks.CYAN_IRON_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_BLUE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.BLUE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.PURPLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.MAGENTA_IRON_CANDLE_HOLDER)
                .add(ModBlocks.PINK_IRON_CANDLE_HOLDER)

                .add(ModBlocks.DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.WHITE_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_GRAY_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.GRAY_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.BLACK_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.BROWN_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.RED_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.ORANGE_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.YELLOW_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.LIME_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.CYAN_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_BLUE_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.BLUE_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.PURPLE_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.MAGENTA_DOUBLE_IRON_CANDLE_HOLDER)
                .add(ModBlocks.PINK_DOUBLE_IRON_CANDLE_HOLDER)

                //GOLDEN CANDLE HOLDER
                .add(ModBlocks.GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.WHITE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_GRAY_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.GRAY_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.BLACK_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.BROWN_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.RED_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.ORANGE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.YELLOW_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.LIME_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.CYAN_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_BLUE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.BLUE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.PURPLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.MAGENTA_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.PINK_GOLDEN_CANDLE_HOLDER)

                .add(ModBlocks.DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.WHITE_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_GRAY_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.GRAY_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.BLACK_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.BROWN_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.RED_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.ORANGE_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.YELLOW_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.LIME_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.CYAN_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_BLUE_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.BLUE_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.PURPLE_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.MAGENTA_DOUBLE_GOLDEN_CANDLE_HOLDER)
                .add(ModBlocks.PINK_DOUBLE_GOLDEN_CANDLE_HOLDER)

                //COPPER CANDLE HOLDER
                .add(ModBlocks.COPPER_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.COPPER_PINK_CANDLE_HOLDER)

                //EXPOSED COPPER CANDLE HOLDER
                .add(ModBlocks.EXPOSED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_COPPER_PINK_CANDLE_HOLDER)

                //WEATHERED COPPER CANDLE HOLDER
                .add(ModBlocks.WEATHERED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_COPPER_PINK_CANDLE_HOLDER)

                //OXIDIZED COPPER CANDLE HOLDER
                .add(ModBlocks.OXIDIZED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_COPPER_PINK_CANDLE_HOLDER)

                //WAXED COPPER CANDLE HOLDER
                .add(ModBlocks.WAXED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_COPPER_PINK_CANDLE_HOLDER)

                //WAXED EXPOSED COPPER CANDLE HOLDER
                .add(ModBlocks.WAXED_EXPOSED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_COPPER_PINK_CANDLE_HOLDER)

                //WAXED WEATHERED COPPER CANDLE HOLDER
                .add(ModBlocks.WAXED_WEATHERED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_COPPER_PINK_CANDLE_HOLDER)

                //WAXED OXIDIZED COPPER CANDLE HOLDER
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_WHITE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_LIGHT_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_GRAY_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_BLACK_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_BROWN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_RED_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_ORANGE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_YELLOW_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_LIME_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_GREEN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_CYAN_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_LIGHT_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_BLUE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_PURPLE_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_MAGENTA_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_COPPER_PINK_CANDLE_HOLDER)

                //Unaffected
                .add(ModBlocks.DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                //Exposed
                .add(ModBlocks.EXPOSED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.EXPOSED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                //Weathered
                .add(ModBlocks.WEATHERED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WEATHERED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                //Oxidized
                .add(ModBlocks.OXIDIZED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.OXIDIZED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                //Waxables
                .add(ModBlocks.WAXED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                .add(ModBlocks.WAXED_EXPOSED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_EXPOSED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                .add(ModBlocks.WAXED_WEATHERED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_WEATHERED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

                .add(ModBlocks.WAXED_OXIDIZED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_WHITE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_LIGHT_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_GRAY_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_BLACK_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_BROWN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_RED_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_ORANGE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_YELLOW_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_LIME_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_GREEN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_CYAN_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_LIGHT_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_BLUE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_PURPLE_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_MAGENTA_DOUBLE_COPPER_CANDLE_HOLDER)
                .add(ModBlocks.WAXED_OXIDIZED_PINK_DOUBLE_COPPER_CANDLE_HOLDER)

        ;
        getOrCreateTagBuilder(BlockTags.AXE_MINEABLE)
                //IRONWOOD
                .add(ModBlocks.IRONWOOD_LOG)
                .add(ModBlocks.STRIPPED_IRONWOOD_LOG)
                .add(ModBlocks.IRONWOOD_PLANKS)
                .add(ModBlocks.IRONWOOD_FENCE)
                .add(ModBlocks.IRONWOOD_FENCE_GATE)
                .add(ModBlocks.IRONWOOD_STAIRS)
                .add(ModBlocks.IRONWOOD_SLAB)
                .add(ModBlocks.IRONWOOD_DOOR)
                .add(ModBlocks.IRONWOOD_TRAPDOOR)
                .add(ModBlocks.IRONWOOD_PRESSURE_PLATE)
                .add(ModBlocks.IRONWOOD_BUTTON)
                .add(ModBlocks.IRONWOOD_SIGN)
                .add(ModBlocks.IRONWOOD_WALL_SIGN)
                .add(ModBlocks.IRONWOOD_HANGING_SIGN)
                .add(ModBlocks.IRONWOOD_WALL_HANGING_SIGN)

                //OLIVE
                .add(ModBlocks.OLIVE_LOG)
                .add(ModBlocks.STRIPPED_OLIVE_LOG)
                .add(ModBlocks.OLIVE_PLANKS)
                .add(ModBlocks.OLIVE_FENCE)
                .add(ModBlocks.OLIVE_FENCE_GATE)
                .add(ModBlocks.OLIVE_STAIRS)
                .add(ModBlocks.OLIVE_SLAB)
                .add(ModBlocks.OLIVE_DOOR)
                .add(ModBlocks.OLIVE_TRAPDOOR)
                .add(ModBlocks.OLIVE_PRESSURE_PLATE)
                .add(ModBlocks.OLIVE_BUTTON)
                .add(ModBlocks.OLIVE_HANGING_SIGN)
                .add(ModBlocks.OLIVE_WALL_HANGING_SIGN)
                .add(ModBlocks.OLIVE_SIGN)
                .add(ModBlocks.OLIVE_WALL_SIGN)

                //CHAIRS
                .add(ModBlocks.OAK_CHAIR)
                .add(ModBlocks.DARK_OAK_CHAIR)
                .add(ModBlocks.BIRCH_CHAIR)
                .add(ModBlocks.SPRUCE_CHAIR)
                .add(ModBlocks.ACACIA_CHAIR)
                .add(ModBlocks.JUNGLE_CHAIR)
                .add(ModBlocks.BAMBOO_CHAIR)
                .add(ModBlocks.CRIMSON_CHAIR)
                .add(ModBlocks.WARPED_CHAIR)
                .add(ModBlocks.IRONWOOD_CHAIR)
                .add(ModBlocks.OLIVE_CHAIR)

                //STOOLS
                .add(ModBlocks.OAK_STOOL)
                .add(ModBlocks.DARK_OAK_STOOL)
                .add(ModBlocks.BIRCH_STOOL)
                .add(ModBlocks.SPRUCE_STOOL)
                .add(ModBlocks.ACACIA_STOOL)
                .add(ModBlocks.JUNGLE_STOOL)
                .add(ModBlocks.BAMBOO_STOOL)
                .add(ModBlocks.CRIMSON_STOOL)
                .add(ModBlocks.WARPED_STOOL)
                .add(ModBlocks.IRONWOOD_STOOL)
                .add(ModBlocks.OLIVE_STOOL)

                //TABLE
                .add(ModBlocks.OAK_TABLE)
                .add(ModBlocks.DARK_OAK_TABLE)
                .add(ModBlocks.MANGROVE_TABLE)
                .add(ModBlocks.BIRCH_TABLE)
                .add(ModBlocks.SPRUCE_TABLE)
                .add(ModBlocks.ACACIA_TABLE)
                .add(ModBlocks.JUNGLE_TABLE)
                .add(ModBlocks.BAMBOO_TABLE)
                .add(ModBlocks.CRIMSON_TABLE)
                .add(ModBlocks.WARPED_TABLE)
                .add(ModBlocks.IRONWOOD_TABLE)
                .add(ModBlocks.OLIVE_TABLE)

                //PAINTED PLANKS
                .add(ModBlocks.BLACK_PAINTED_PLANKS)
                .add(ModBlocks.BLUE_PAINTED_PLANKS)
                .add(ModBlocks.BROWN_PAINTED_PLANKS)
                .add(ModBlocks.CYAN_PAINTED_PLANKS)
                .add(ModBlocks.GRAY_PAINTED_PLANKS)
                .add(ModBlocks.GREEN_PAINTED_PLANKS)
                .add(ModBlocks.LIGHT_BLUE_PAINTED_PLANKS)
                .add(ModBlocks.LIME_PAINTED_PLANKS)
                .add(ModBlocks.MAGENTA_PAINTED_PLANKS)
                .add(ModBlocks.ORANGE_PAINTED_PLANKS)
                .add(ModBlocks.PINK_PAINTED_PLANKS)
                .add(ModBlocks.PURPLE_PAINTED_PLANKS)
                .add(ModBlocks.RED_PAINTED_PLANKS)
                .add(ModBlocks.LIGHT_GRAY_PAINTED_PLANKS)
                .add(ModBlocks.WHITE_PAINTED_PLANKS)
                .add(ModBlocks.YELLOW_PAINTED_PLANKS)

                //AGRICULTURE
                .add(ModBlocks.STAKE)
                .add(ModBlocks.CRUSHING_TUB)
                .add(ModBlocks.LIQUID_BARREL)

        ;
        getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE)
                .add(ModBlocks.FERTILE_SOIL)
                .add(ModBlocks.CLAY_WALL)
                .add(ModBlocks.CLAY_WALL_CROSS)
                .add(ModBlocks.CLAY_WALL_DIAGONAL)
        ;
        getOrCreateTagBuilder(BlockTags.CEILING_HANGING_SIGNS)
                .add(ModBlocks.IRONWOOD_HANGING_SIGN)
                .add(ModBlocks.OLIVE_HANGING_SIGN)

        ;
        getOrCreateTagBuilder(BlockTags.WALL_HANGING_SIGNS)
                .add(ModBlocks.IRONWOOD_WALL_HANGING_SIGN)
                .add(ModBlocks.OLIVE_WALL_HANGING_SIGN)

        ;
        getOrCreateTagBuilder(BlockTags.WALL_SIGNS)
                .add(ModBlocks.IRONWOOD_WALL_SIGN)
                .add(ModBlocks.OLIVE_WALL_SIGN)

        ;
        getOrCreateTagBuilder(BlockTags.LOGS_THAT_BURN)
                //IRONWOOD
                .add(ModBlocks.IRONWOOD_LOG)
                .add(ModBlocks.IRONWOOD_PLANKS)
                .add(ModBlocks.STRIPPED_IRONWOOD_LOG)
                //OLIVE
                .add(ModBlocks.OLIVE_LOG)
                .add(ModBlocks.OLIVE_WOOD)
                .add(ModBlocks.STRIPPED_OLIVE_LOG)
        ;
        getOrCreateTagBuilder(BlockTags.FENCES)
                .add(ModBlocks.IRONWOOD_FENCE)
                .add(ModBlocks.OLIVE_FENCE);

        getOrCreateTagBuilder(BlockTags.FENCE_GATES)
                .add(ModBlocks.IRONWOOD_FENCE_GATE)
                .add(ModBlocks.OLIVE_FENCE_GATE);

        getOrCreateTagBuilder(BlockTags.WALLS)
                .add(ModBlocks.COBBLED_SLATE_WALL)
                .add(ModBlocks.POLISHED_SLATE_WALL)
                .add(ModBlocks.SLATE_BRICK_WALL)
                .add(ModBlocks.POLISHED_STONE_WALL)
                .add(ModBlocks.ANDESITE_BRICK_WALL)
                .add(ModBlocks.DIORITE_BRICK_WALL)
                .add(ModBlocks.GRANITE_BRICK_WALL)
                .add(ModBlocks.SANDSTONE_BRICK_WALL)
                .add(ModBlocks.RED_SANDSTONE_BRICK_WALL)
        ;
        getOrCreateTagBuilder(BlockTags.CLIMBABLE)
                .add(ModBlocks.ROPE)
        ;
        getOrCreateTagBuilder(ModTags.Blocks.PRESERVES_FARMLAND)
                .add(ModBlocks.STAKE)
                .add(ModBlocks.CHILI_CROP)
                .add(ModBlocks.TOMATO_CROP)
        ;
        getOrCreateTagBuilder(BlockTags.BAMBOO_PLANTABLE_ON)
                .add(ModBlocks.FERTILE_SOIL)
        ;
        getOrCreateTagBuilder(BlockTags.LEAVES)
                .add(ModBlocks.IRONWOOD_LEAVES)
                .add(ModBlocks.OLIVE_LEAVES)
                .add(ModBlocks.APPLE_LEAVES)
        ;
        getOrCreateTagBuilder(ModTags.Blocks.FERTILE_SOILS)
                .add(ModBlocks.FERTILE_SOIL)
        ;
        getOrCreateTagBuilder(ModTags.Blocks.ALLOWS_GROWTH)
                .add(Blocks.DIRT)
                .add(Blocks.GRASS_BLOCK)
                .add(Blocks.PODZOL)
                .add(Blocks.FARMLAND)
        ;
        getOrCreateTagBuilder(ModTags.Blocks.EVAPORATING_BOOSTERS)
                .add(Blocks.MAGMA_BLOCK)
                .add(Blocks.FIRE)
        ;
    }
}
